- ConversionTools/convert_database.py
- ConversionTools/convert_database.ui
- CustomWidgets/connectionWidget.py
- Factories/DbFactory/abstractDb.py
- Factories/DbFactory/dbFactory.py
- Factories/DbFactory/postgisDb.py
- Factories/DbFactory/spatialiteDb.py
- Factories/SqlFactory/postgisSqlGenerator.py
- Utils/utils.py
- dsg_tools.py
> Abstract db refactory branch

- VectorTools/contour_tool.py
- VectorTools/contour_value.py
- VectorTools/contour_value.ui
Adds a dialog to put an initial value when the first feature attribute is null
> CONTOUR_TOOL 

- Factories/DbFactory/postgisDb.py
- Factories/SqlFactory/postgisSqlGenerator.py
- ValidationTools/validation_toolbox.py
- ValidationTools/validation_toolbox.ui
- testes.py
Pull request da limpeza de flags feito pelo @jpesperidiao
> 3.1 dev clear flags

- AttributeTools/code_list.py
- AttributeTools/code_list.ui
CodeListViewer agora não está mais conectado com o sinal de troca de camada ativa, resolvendo o problema levantado.
Pequena mudança na GUI. (mudar a aparência antes do merge?)
> 3.1 dev code listand values #196

- CustomWidgets/genericManagerWidget.py
- CustomWidgets/listSelector.py
- Factories/DbFactory/postgisDb.py
- Factories/SqlFactory/postgisSqlGenerator.py
- ValidationTools/validation_toolbox.py
- ValidationTools/validation_toolbox.ui
Reverts dsgoficial/DsgTools#217
> Revert "3.2 dev validation tool box #209"

- ProductionTools/CopyPasteTool/multiLayerSelect.py
- Alt behaviour added to 3.2 dev; and
- #68 closed.
> 3.2 dev generic selection #68

- Factories/SqlFactory/postgisSqlGenerator.py
- ValidationTools/ValidationProcesses/spatialRuleProcess.py
- ValidationTools/ValidationRules/ruleLibrary.rul
- ValidationTools/processParametersDialog.py
- ValidationTools/validationManager.py
Cardinality may be left empty now
> 3.2 dev validation toolbox #77

- ProductionTools/CopyPasteTool/multiLayerSelect.py
Context menu adaptable to #classes and featuers, also takes selected and non-selected feature status into consideration.
> 3.2 dev generic selection tool #240

- ProductionTools/DsgRasterInfoTool/assignBandValueTool.py
- ProductionTools/DsgRasterInfoTool/dsgRasterInfoTool.py
From Raster Point Setter tool bug (#277 ) fixed
> 3.2 dev validation tool box from raster value setter

- core/DSGToolsProcessingAlgs/Algs/ValidationAlgs/createNetworkNodesAlgorithm.py
- core/DSGToolsProcessingAlgs/Algs/ValidationAlgs/identifyGapsAlgorithm.py
- core/DSGToolsProcessingAlgs/Algs/ValidationAlgs/identifyOutOfBoundsAnglesInCoverageAlgorithm.py
- core/DSGToolsProcessingAlgs/Algs/ValidationAlgs/identifyOverlapsAlgorithm.py
- core/DSGToolsProcessingAlgs/Algs/ValidationAlgs/removeDuplicatedFeaturesAlgorithm.py
- core/DSGToolsProcessingAlgs/Algs/ValidationAlgs/removeSmallLinesAlgorithm.py
- core/DSGToolsProcessingAlgs/Algs/ValidationAlgs/verifyNetworkDirectioningAlgorithm.py
- core/DSGToolsProcessingAlgs/dsgtoolsProcessingAlgorithmProvider.py
- core/GeometricTools/networkHandler.py
- gui/ProductionTools/Toolbars/InspectFeatures/inspectFeatures.py
- gui/ProductionTools/Toolboxes/AttributeTools/code_list.py
- Criado um ponto de vala com fluxo entrando ou saindo;
- Adicionado black list de atributos para as drenagens tanto no processo de criação quanto no processo de direcionamento;
- Adicionados feedbacks para barra de progresso no processing;
- Bug fixes em alguns processos de validação;
> Reestruturação do Direcionamento para uso com Valas

- ProductionTools/Acquisition/distanceToolTip.py
- ProductionTools/Acquisition/geometricaAquisition.py
- ProductionTools/Acquisition/polygon.py
- options.py
- options.ui
This commit makes the minimun distance segment editable in options and blocks aquisition of features with segments smaller than the minimun distance.
> Right Angle Tool - upgrade

- gui/AboutAndFurtherInfo/Options/options.py
- gui/AboutAndFurtherInfo/Options/options.ui
- gui/ProductionTools/MapTools/Acquisition/distanceToolTip.py
- gui/ProductionTools/MapTools/Acquisition/geometricaAquisition.py
- gui/ProductionTools/MapTools/Acquisition/polygon.py
- gui/ProductionTools/MapTools/FreeHandTool/models/acquisitionFree.py
Atualização da ferramenta de aquisição com ângulos retos do DSGTools v3.2 migrado para o v4.0dev.
> Qgis3.0 migration #321

- core/Factories/LayerLoaderFactory/edgvLayerLoader.py
- core/GeometricTools/layerHandler.py
- gui/CustomWidgets/ConnectionWidgets/AdvancedConnectionWidgets/connectionComboBox.py
- gui/CustomWidgets/ConnectionWidgets/connectionWidget.py
- gui/CustomWidgets/DatabasePropertiesWidgets/BasicPropertyWidgets/databaseParameterWidget.py
- gui/CustomWidgets/DatabasePropertiesWidgets/BasicPropertyWidgets/genericManagerWidget.py
- gui/CustomWidgets/DatabasePropertiesWidgets/BasicPropertyWidgets/permissionWidget.py
- gui/CustomWidgets/DatabasePropertiesWidgets/CompactPropertyWidgets/genericCompactPropertyManagerWidget.py
- gui/CustomWidgets/SelectionWidgets/customSelector.py
- gui/DatabaseTools/ConversionTools/datasourceConversion.py
- gui/DatabaseTools/UserTools/serverProfilesManager.py
- gui/LayerTools/CreateFrameTool/ui_create_inom_dialog.py
- gui/ProductionTools/Toolbars/DsgRasterInfoTool/assignBandValueTool.py
- gui/ProductionTools/Toolbars/StyleManagerTool/styleManagerTool.py
- gui/ProductionTools/Toolboxes/FieldToolBox/field_setup.py
- gui/ProductionTools/Toolboxes/FieldToolBox/field_toolbox.py
- gui/ServerTools/batchDbManager.py
- gui/ServerTools/selectStyles.py
Soluções para o #325 e alguns do #324.
Alguns outros _bugs_ foram identificados e solucionados.
> Qgis3.0 migration #325

- core/DbTools/bodyConversionSummaryTemplate.html
- core/DbTools/dbConverter.py
- core/Factories/DbFactory/postgisDb.py
- core/Factories/DbFactory/spatialiteDb.py
- gui/CustomWidgets/ConnectionWidgets/AdvancedConnectionWidgets/connectionComboBox.py
- gui/CustomWidgets/ConnectionWidgets/AdvancedConnectionWidgets/newConnectionLineEdit.py
- gui/CustomWidgets/DatabaseConversionWidgets/SupportedDrivers/newGeopackageWidget.py
- gui/CustomWidgets/DatabaseConversionWidgets/SupportedDrivers/newPostgisWidget.py
- gui/CustomWidgets/DatabaseConversionWidgets/SupportedDrivers/newShapefileWidget.py
- gui/CustomWidgets/DatabaseConversionWidgets/SupportedDrivers/newSpatialiteWidget.py
- gui/DatabaseTools/ConversionTools/datasourceConversion.py
- gui/ServerTools/viewServers.py
- A few unnecessary open connections were handled
- fixed #329 
- fixed default server from DSGTools not matching QSettings
> Qgis3.0 migration db con excess

- core/DSGToolsProcessingAlgs/Algs/ValidationAlgs/identifyDuplicatedFeaturesAlgorithm.py
- core/DSGToolsProcessingAlgs/Algs/ValidationAlgs/identifyDuplicatedGeometriesAlgorithm.py
- core/DbTools/dbConverter.py
- core/GeometricTools/layerHandler.py
Conserta a barra de progresso do geometria duplicada e resolve bug de não identificação de feições duplicadas.
> Qgis3.0 migration #385

- core/DSGToolsProcessingAlgs/Algs/EditingAlgs/createEditingGridAlgorithm.py
- core/EditingTools/gridAndLabelCreator.py
works only with SIRGAS2000 UTM projected layers
> code update

- gui/ProductionTools/MapTools/FreeHandTool/controllers/acquisitionFreeController.py
- metadata.txt
Reshape dava erro ao ser usado com feições do tipo polígono.
> fixed reshape not working with polygons

- core/DSGToolsProcessingAlgs/Algs/ValidationAlgs/identifyWrongBuildingAnglesAlgorithm.py
- core/DSGToolsProcessingAlgs/dsgtoolsProcessingAlgorithmProvider.py
- core/GeometricTools/geometryHandler.py
Os testes vou fazer depois (todos os que estou devendo)
> identify out of bounds angles in buildings

- core/DSGToolsProcessingAlgs/Algs/ValidationAlgs/identifyDuplicatedFeaturesAlgorithm.py
- core/DSGToolsProcessingAlgs/Algs/ValidationAlgs/identifyDuplicatedGeometriesAlgorithm.py
@jpesperidiao acho que agora tá resolvido (rodei os unittests e não quebrei nada =] )
> feedback fix

- core/DbModels/PostGIS/213_Pro/edgv213_pro.sql
- core/Factories/DbFactory/postgisDb.py
- gui/CustomWidgets/ConnectionWidgets/ServerConnectionWidgets/customServerConnectionWidget.py
- Atualiza a SQL da EDGV 2.1.3 Pro (#437);
- sugestão de conserto de _typo_: "Postdam 1930" -> "Potsdam 1930"; e
- conserta modelagem 2.1.3 Pro sendo identificada como "Outras modelagens" pelo `Layer Loader`.
> Dev edgv213 pro update

- gui/CustomWidgets/OrderedPropertyWidgets/orderedTableWidget.py
- gui/CustomWidgets/OrderedPropertyWidgets/orderedTableWidget.ui
- gui/ProcessingUI/enforceSpatialRuleWrapper.py
Added load/save attributes directly to ```OrderedTableWidget```.
> Dev otw rework

- core/DSGToolsProcessingAlgs/Models/qualityAssuranceWorkflow.py
No tests added.
Fixed Workflow's parameters being ordered before exported.
> fixed #476

- core/Factories/DbFactory/postgisDb.py
- gui/CustomWidgets/BasicInterfaceWidgets/buttonPropWidget.py
- gui/CustomWidgets/SelectionWidgets/selectFileWidget.py
- gui/DatabaseTools/DbTools/BatchDbCreator/createBatchFromCsv.py
- gui/ProductionTools/MapTools/FreeHandTool/controllers/acquisitionFreeController.py
- gui/ProductionTools/Toolboxes/CustomFeatureToolBox/customFeatureTool.py
Fixed:
- free hand edit command not available -> freehand on Custom Feature Tool Box wasn't working properly;
- EDGV 2.1.3 Pro created instead of 3.0 on db creation tool;
- CSV batch db creation not working properly;
- error raised when an attribute with map value had a misinformed value on CFT importing setup dialog; and
- feature extraction wasn't working properly when used with QGIS default extraction tool on QGIS versions previous to 3.15.
> Dev bug hunting

- core/DSGToolsProcessingAlgs/Algs/OtherAlgs/runRemoteFMEAlgorithm.py
- gui/CustomWidgets/ProcessingParameterWidgets/fmeManagerWidget.py
- gui/CustomWidgets/ProcessingParameterWidgets/fmeManagerWidget.ui
Refactored code to follow the DSGTools coding style guidelines and fixed FME Remote algo not running without proxy.
> Dev #545 pr complementation

- core/DSGToolsProcessingAlgs/Algs/ValidationAlgs/topologicalCleanAlgorithm.py
- core/GeometricTools/layerHandler.py
- dsg_tools.py
- metadata.txt
Corrigido o #551.
O problema estava que, quando se separou em rotinas para polígono e linhas, utilizou-se um método como do outro. Nisto, manteve-se o uso de geometria do tipo polígono sempre como saída, o que fazia com que se perdessem as geometrias do tipo linha.
@dinizime, se puder confirmar a resolução, fico no aguardo para encerrar o _issue_.
> updated debugger module to debugpy and fixed #551

- core/NetworkTools/BDGExRequestHandler.py
Conversando com @maurelioc, percebemos que houve uma atualização do serviço com relação à tag que entrega o CRS. Isto parece resolver o problema.
> fixed WFS layers not loading properly

- gui/ProductionTools/MapTools/Acquisition/distanceToolTip.py
- gui/ProductionTools/MapTools/Acquisition/geometricaAquisition.py
- gui/ProductionTools/MapTools/Acquisition/polygon.py
- gui/ProductionTools/MapTools/FreeHandTool/models/acquisitionFree.py
- gui/ProductionTools/Toolbars/MinimumAreaTool/minimumAreaTool.py
- gui/ProductionTools/Toolbars/MinimumAreaTool/shapeTool.py
O método de reshape não estava considerando a possibilidade de multipartes. Adicionado a verificação.
> fixed free hand not handling multigeometry layer

- gui/ProductionTools/Toolboxes/CustomFeatureToolBox/customFeatureTool.py
> "fixed" feature duplication when qgis in pt-br, pt-pt and es

- DsgTools/core/DSGToolsProcessingAlgs/Algs/ValidationAlgs/identifyDrainageFlowIssues.py
- DsgTools/core/DSGToolsProcessingAlgs/dsgtoolsProcessingAlgorithmProvider.py
New Processing Algo:
Drainage Flow Issues
It checks for the following issues on the drainage flow (and flags them):
- 4 or more lines conecting on a point
- 2 or 3 lines total, but no lines leaving a point
- 2 or 3 lines total, but no lines entering a point
> Drainage Flow Issues

- DsgTools/core/DSGToolsProcessingAlgs/Algs/ValidationAlgs/identifyDrainageAngleIssues.py
- DsgTools/core/DSGToolsProcessingAlgs/dsgtoolsProcessingAlgorithmProvider.py
New Processing Algo:
Drainage Angle Issues
It checks for and flags sharp turns on drainage flow intersections.
(A sharp turn is considered to be a direction change greater than 90 degrees)
> Drainage Angle Issues

- DsgTools/gui/ServerTools/batchDbManager.py
Bug fix - to many values to extract expected  2 e ainda a versão do Banco está escrito "EDGV 3.0 Pro" em vez de "3.0 Pro".
> Bug fix - to many values to extract expected  2

- CHANGELOG.md
- DsgTools/core/DSGToolsProcessingAlgs/Algs/ValidationAlgs/hierarchicalSnapLayerOnLayerAndUpdateAlgorithm.py
- DsgTools/core/DSGToolsProcessingAlgs/algRunner.py
- DsgTools/metadata.txt
> Versão 4.9.17: snap hierárquico agora adiciona vértice na referência e na camada atraída

- CHANGELOG.md
- DsgTools/core/DbModels/PostGIS/3_Pro/edgv3_pro.sql
- DsgTools/core/Factories/DbCreatorFactory/spatialiteDbCreator.py
- DsgTools/core/Factories/DbFactory/postgisDb.py
- DsgTools/core/Factories/SqlFactory/postgisSqlGenerator.py
- DsgTools/gui/CustomWidgets/ConnectionWidgets/AdvancedConnectionWidgets/connectionComboBox.py
- DsgTools/gui/CustomWidgets/ConnectionWidgets/AdvancedConnectionWidgets/databaseFileLineEdit.py
- DsgTools/gui/CustomWidgets/DatabasePropertiesWidgets/BasicPropertyWidgets/databaseParameterWidget.ui
- DsgTools/metadata.txt
- README.md
Melhoria:
- Adicionado o modelo EDGV 3.0 Pro;
Correção de Bug:
- Correção de erro ao criar banco EDGV 3.0;
> Versão 4.10.1

- CHANGELOG.md
- DsgTools/core/DSGToolsProcessingAlgs/Algs/OtherAlgs/createFramesWithConstraintAlgorithm.py
- DsgTools/metadata.txt
O processo de gerar moldura sistemática à camada relaciona agora suporta a entrade de camadas do tipo ponto e linha
> Versao 4.17.18: O processo de gerar moldura sistemática à camada relaciona agora suporta a entrade de camadas do tipo ponto e linha

- CHANGELOG.md
- DsgTools/gui/ProductionTools/Toolboxes/MultiLayersCentroidsFlagTool/multiLayersCentroidsFlagTool.py
- DsgTools/metadata.txt
Change centroids outside the flag bug fix
> Versão 4.17.44:  change centroids outside the flag bug fix
